services:
    db:
        container_name: mysql
        image: mysql:9.5
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - web-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 1G

volumes:
    db-data:
        driver: local
